server:
  port: 3333

spring:
  datasource:
    url: jdbc:mysql://thefaco-beverage.cry75t3vojiz.ap-northeast-2.rds.amazonaws.com:3306/beyerage?useUnicode=yes&characterEncoding=UTF-8
    username: admin
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true